### ISSUE TITLE
Incorrect identification

### ISSUE THREAD

**Issue by xnolnocpac** [phishai/idn-protect-chrome#2]
Hello,
The phish.Ai chrome browser is labeling my website www.olénoé.com as a malicious website simply because it is an internationalized domain name (IDN). My website is not malicious, it uses Spanish words in the title. I think it is inappropriate to label all IDNs as malicious websites when in fact IDNs are helping make the web more linguistically diverse. Why am I being penalized?

**Comment by yevgenypats** [comment]
Hey There,
[Here](https://www.reddit.com/r/netsec/comments/870pk7/open_source_chrome_extension_to_alert_idnunicode/) is the full discussion on reddit.
TLDR:
1) I don't say that every IDN website is malicious I just alert that this use an IDN as chrome browser doesnt show any sign of this.
2) I did mention that currently this extension is more useful to English users.
3) We will Add whitelist features to whitelist domains (and still it will become a burden for users who constantly use IDN websites)
4) As we add more features to this plugin I'll add opt-in opt-out for this one so users can opt-out from the IDN alert if they wish.

Best,
Yevgeny

**Comment by yevgenypats** [comment]
Looks like the discussion moved to #3. I'm closing this issue.
